name: Restart Redfin-Scraper Service

on:
  push:
    branches:
      - main

jobs:
  pull_and_restart:
    runs-on: ubuntu-latest
    steps:
      - name: remotely restart redfin-scraper service
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          command: |
            systemctl restart redfin-scraper
